#!/bin/sh
#
#
# FOooo
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  universal-ctags --tag-relative -L - -f"$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
