#!/usr/bin/env bash

$HOME/bin/refresh_display.sh
$HOME/bin/srandrd $HOME/bin/refresh_display.sh

xsetroot -cursor_name left_ptr

lxpolkit &
picom &
nm-applet &

1password --silent &
urxvt &

xss-lock $HOME/.dotfiles/bin/lock-and-turn-off-display.sh &

xinput set-prop "ELAN0672:00 04F3:3187 Touchpad" "libinput Tapping Enabled" 1
libinput-gestures-setup start

sleep 1 && xmodmap $HOME/.dotfiles/x/modcapslock
